### ISSUE TITLE
Create model that is not in main

### ISSUE THREAD

**Issue by RobertBrunhage** [brianegan/scoped_model#18]
I have an application which I don't want my model to be created in the beginning. I want to create my model etc when I am navigated to a logged in, state (Home.dart). Here I want to initialize the model, but when I try to find it with ScopedModelDescendant in a navigated class it returns null. How do I know if a widget is a child of a parent? And do I have to have the model at MaterialApp?

**Comment by brianegan** [comment]
If you want to share the model across different Screens in your app, the `ScopedModel` will need to wrap the `MaterialApp` or `WidgetsApp`. This is because the `MaterialApp` creates all screens when you use `Navigator.push` etc, and therefore the `ScopedModel` needs to be a parent of all screens.

If you only want to use the Model on a Single screen, you can create it in the Root Widget of a Screen (e.g. Home.dart) and all children of that Widget will have access to the ScopedModel.

If you don't want to create the Model until you log in, your `MyApp` Widget which creates the `MaterialApp` could be a stateful widget. When the login occurs, you could do a `setState` on the `MyApp` widget with some information about the login and then wrap the `MaterialApp` with a scoped model on rebuild if the data exists.

Another way to approach this problem: Create your ScopedModel when the app starts, and use it to drive the login process. This means: When the user logs in, do it with your `Model` class  -- e.g. call `userMiddleware.login(user, pass)`. If it succeeds, update the data in the model and navigate to the home screen (or any screen) and fetch the data from the Model with a `ScopedModelDescendant`.

**Comment by brianegan** [comment]
Heya @RobertBrunhage -- did this help out? If so, I can go ahead and close it out. If not, please feel free to write back!

**Comment by RobertBrunhage** [comment]
I solved the issue with creating a empty object in main and passing that to my home page with this:

'/home': (BuildContext context) => new Home(widget.user),

after that in home I can initialize the user, don't know if this is a good solution but works pretty good :)
