### ISSUE TITLE
Simple question about control widget values

### ISSUE THREAD

**Issue by willismonroe** [brianegan/scoped_model#19]
I'm experimenting with the scoped_model system for designing an app, and I have a very simple question about how to initialize and change the value fields of widgets like DropDownButton and Switch.

I have a model structure that contains a list of options for the DropdownButton, I wrap the button in the ScopedModelDescendant so I can access the list within the model to create the DropdownMenuItem's necessary.  However I need to give the DropdownButton an initial value that is mutable (so that selecting options updates the widget).  I'm struggling to figure out where to store that variable and how to initialize it.

One option is to store in the local widget's state, but an initState() method does give me access to the existing list of categories in the model.  If I put it in the build() method for the widget, it can access the model, but then I can't change it because the build() method will overwrite any changes made by the widget's setState().  I guess the third option would be to put a mutable variable in the model itself that reflects the state of the widget, but I'm not sure if that's following proper design principles.

I've created a small sample app below, and inserted my two questions with double stars (**)

```import 'package:flutter/material.dart';
import 'package:scoped_model/scoped_model.dart';

class MyAppModel extends Model {
  List<String> categories = ['A', 'B', 'C'];
}

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ScopedModel<MyAppModel>(
        model: MyAppModel(),
        child: MaterialApp(
            home: Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text('Dropdown button from model:'),
                MyAppDropdown(),
              ],
            ),
          ),
        )));
  }
}

class MyAppDropdown extends StatefulWidget {
  @override
  _MyAppDropdownState createState() => _MyAppDropdownState();
}

class _MyAppDropdownState extends State<MyAppDropdown> {
  @override
  Widget build(BuildContext context) {
    return ScopedModelDescendant<MyAppModel>(
      builder: (context, child, model) {
        return Container(
          child: DropdownButton(
            value: **"How do I insert a local mutable value from the model"**
            items: model.categories.map((String value) {
              return DropdownMenuItem<String>(value: value, child: Text(value));
            }).toList(),
            onChanged: **"How do I change that local mutable value"**,
          ),
        );
      },
    );
  }
}

```

**Comment by brianegan** [comment]
Hi @willismonroe!

I usually put that type of logic in the `Model` itself, with a getter/setter pair. In the Widget, I just call `model.currentValue = selectedValue` within the `onChanged` callback of a `DropDownButton`.

The reason I put it in the model? Generally, you'll want the selected value to affect other things in the Model as well! For example, in a Todo app, if you use a DropdownButton to filter the results, you'll want to use that Filter to limit the number of items displayed, and those items are generally contained in the Model as well. Therefore, in that case, it makes more sense to put this value in the Model as a mutable value rather than in a State class, so you can synchronize all that logic.

I've got an example of a PopupMenuButton that does exactly this type of thing in my Architecture Samples Repo with a PopupMenuButton, but the concepts should be basically the same:

  1. The model class get / set methods: https://github.com/brianegan/flutter_architecture_samples/blob/master/example/scoped_model/lib/widgets/filter_button.dart#L25
  2. Usage in the Widget: https://github.com/brianegan/flutter_architecture_samples/blob/master/example/scoped_model/lib/widgets/filter_button.dart#L20

Hope that helps! Let me know if it does, or if ya have follow up questions :)

**Comment by willismonroe** [comment]
Hi @brianegan 

Thanks so much, that's super useful and explained very clearly.  I can see the usage in your code, and the reasoning behind storing the active selection in the model.  I'm realizing now that having this stored makes a lot more sense, for instance in my app, the data entry widgets are on the home screen (including this DropdownButton), but you can pull a drawer over it and delete items from the dropdown list.  In that case I'd want to what the user had selected, so I can change the selected value if that's the one to be deleted.

Appreciate you taking the time to answer my question!
All the best.
