### ISSUE TITLE
Depending on context doesn't trigger rebuild/changes?

### ISSUE THREAD

**Issue by pyros2097** [brianegan/scoped_model#29]
Using the second method `ScopedModel.of`. I'm able to change the state of the model but the changes do not update children accessing the model using context. It works if I use the scoped descendant widget. Is this the expected behavior.
I have a test for this,
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:scoped_model/scoped_model.dart';

void main() {
  testWidgets("model change should update children widgets depending on context", (WidgetTester tester) async {
    var testModel = new TestModel();

    var tree = new MaterialApp(
      home: new ScopedModel<TestModel>(
        model: testModel,
        child: new Container(
          child: TestWidget(),
        ),
      ),
    );

    // initial drawing shows the counter form the model
    await tester.pumpWidget(tree);
    expect(find.text('0'), findsOneWidget);
    // Increment the model, which should rebuild only the listening descendant subtree
    testModel.increment();
    await tester.pump();
    await tester.pump();

    // the text changes correctly
    expect(find.text("1"), findsOneWidget);
  });
}

class TestModel extends Model {
  int _counter;

  TestModel([int initialValue = 0]) {
    _counter = initialValue;
  }

  static TestModel of(BuildContext context) => ScopedModel.of<TestModel>(context);

  int get counter => _counter;

  void increment([int value]) {
    _counter++;
    notifyListeners();
  }
}

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var model = TestModel.of(context);
    return new Container(
      child: Text(model.counter.toString(), textDirection: TextDirection.ltr),
    );
  }
}
```

**Comment by brianegan** [comment]
Yep, that's expected. You need to pass through `rebuildOnChange: true` as part of your call to ScopedModel, or it will only grab the value the first time. I'm considering adding a `listen` or `on` method instead to make this a bit clearer.

E.g. you need to change this:

```dart
static TestModel of(BuildContext context) => ScopedModel.of<TestModel>(context);
```

to this:

```
static OtherTestModel of(BuildContext context) =>
      ScopedModel.of<OtherTestModel>(context, rebuildOnChange: true););
```

**Comment by talksik** [comment]
@brianegan I was stuck on a really weird problem related to this.

I have a complicated model which has a big map of data. I was using this way of doing things
```   // set up bottom sheet console log
    final linesModel =
        ScopedModel.of<LinesModel>(context, rebuildOnChange: false);
    final authUserModel =
        ScopedModel.of<AuthUserModel>(context, rebuildOnChange: false);
    final presenceModel =
        ScopedModel.of<PresenceModel>(context, rebuildOnChange: true);
```

However, I was using the above outside of the build method and in a lifecycle method, and I have one of the rebuildOnChange set to true for presenceModel. Children of widgets in the build method changed something in the presenceModel and so the build method re-mounted. 
So the observation is that even if you use this direct access way in a lifecycle method instead of descendent, and you put rebuildOnChange/listen as true, it causes the build method to run again and hence calling the initState of all children widget again.

However, my weird problem was that this caused an infinite loop in android but not on web. I was stuck on it for hours and can't figure out why on android, children widgets would keep remounting/their initstate kept getting called in an infinite loop as they were updating presenceModel data. I had to change the rebuildOnChange to false for android to stop the loop. However, in flutter run web/chrome, the infinite loop never happened. 

Am I missing something fundamental about flutter? Or something fundamental about platforms? Or something fundamental about scoped_model specifically as it relates to web vs. android?

Please help, I'm really stuck on why flutter is inconsistent on both platforms. I chose flutter because I thought it would be super consistent.
