### ISSUE TITLE
Child models in a list listeners

### ISSUE THREAD

**Issue by paqio** [brianegan/scoped_model#33]
Hello,

As far as i see, if chil List of some model is updated, parent does not notice that. To work around, i am calling notifyListeners of model from the widget. How bad is it and why?

**Comment by brianegan** [comment]
Oh dang, somehow missed this one :/ Yah, this is one of the quirks of scoped_model: You need to be careful about when data changes and call `notifyListeners` at the right time. For your scenario, I don't think there's a way around it, since scoped_model can't do any fancy change detection / notifications.
