### ISSUE TITLE
Sending an action with notifyListeners()

### ISSUE THREAD

**Issue by edodso2** [brianegan/scoped_model#45]
Is there any reason the notifyListeners call cannot contain a parameter that listeners could use to determine what has been updated?

For example if I have two models that I am composing into a root or 'MainModel' via mixins it would be cool if I could have the MainModel listen for updates to the model and in turn persist the correct model data to disk as opposed to the entire model. For example:

```
class MainModel extends Model with UserModel, ProductsModel {
  Service service;

  MainModel(this.service) {
    addListener((String action) {
      if (action == 'USER_MODEL_UPDATED') {
        service.persistUserData(userData);
      } else if (action == 'PRODUCTS_MODEL_UPDATED') {
        service.persistProductData(productData);
      }
    });
  }
}

mixin UserModel on Model {
  userData;

  ...
}

mixin ProductsModel on Model {
  productsData;

  ...
}
```

Any thoughts on this?

**Comment by brianegan** [comment]
Hey there -- since the Model class implements the `Listenable` interface from Flutter, which defines `notifyListeners` as a method that accepts no parameters, I'm not sure we can support this. 

That said, I'm actually wondering: What's the benefit of combining the two models into one `MainModel`?  If they were separate models, you would't have to worry about this particular challenge. Furthermore, if the UI only depends on the UserModel, you wouldn't want it to rebuild when the ProductsModel changes. Therefore, to solve that problem, this type of conditional logic would start to pop up more and more. In my opinion, it's just a bit simpler to keep the two Models properly separated.

If you need to access data from both models in your UI layer, you can still do that in your build methods by using a `ScopedModelDescendant` Widgets or the `ScopedModel.of` method.

Sure, you might need an extra `ScopedModel` Widget or two in your tree, but I think it makes almost everything else easier.

**Comment by edodso2** [comment]
I appreciate the reply. I should have spent more time reading the source code. The User and Products model I came up with for the sake of this example but I could see that the pattern would be to provide the User model at the root of the app (assuming all the child widgets need it) then provide the Products model further down the widget tree where it is needed. 

I have a lot of refactoring to do but I am confident about this approach now.
