### ISSUE TITLE
Todo Example, update a single todo will make the whole todo list re-render.

### ISSUE THREAD

**Issue by jiangbodev** [brianegan/scoped_model#50]
I am a newbie to flutter.

I found the TodosModel is a big model include all todos in the list, so there is no `todoUpdated` or `todoListUpdated`.

is that possible I can distinguish this 2 updates? so I could just re-build the updated todo item, not the all todo list? It should make the performance better.

Could you share us an example for that?

**Comment by brianegan** [comment]
Hey there -- not sure if you were still curious since the issue is closed, but you could definitely do that! 

I don't quite have the time to code up an entire example, but as a general idea: You need to turn each item in the List from a `Todo` into a `TodoModel.` Each item in the list should listen to the Todo Model for changes, and rebuild when it changes. The List itself still needs to listen for changes as well! However, rather than notifying it's listeners when an item changes, it would only need to notify listeners when an item is added or removed (so the entire list can be recalculated at that point, since an item could be inserted or removed at any index).

Overall, I actually tried that approach as well, but it led to the code being a bit more complicated in the end and wasn't any faster on an old device that I was playing with.  Therefore, I kept the example a bit simpler. Perhaps on an app that displays very large or infinite lists, it'd be a good idea to perform that optimization and pay the price of managing a bit more code!
