### ISSUE TITLE
ScopedModel.of vs ScopedModelDescendant usage

### ISSUE THREAD

**Issue by Edorin9** [brianegan/scoped_model#55]
I think the answers to these questions(mostly related to which widget rebuilds) would be a good extension to the documentation. I suggest we add some clarity with the usage including some advantages/disadvantages in our nice docs

### **I.**
```
@override
Widget build(BuildContext context) {
  // ScopedModel.of<HomeModel>(context, rebuildOnChange: true); under the hood
  final model = HomeModel.of(context);
  return Scaffold(
    appBar: AppBar(
      title: Text(
        'A = model.countA}
      ),
    ),
  );
}
```
**Question:**
Will the whole Scaffold rebuild if model.countA's value changes? If not, which child widget will be rebuilt on value change?

> 

> 

> 

### **II.**
**a.**
```
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text(
        'A = HomeModel.of(context).countA}
      ),
    ),
  );
}
```
**b.**
```
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: ScopedModelDescendant<HomeModel>(
        builder: (context, child, model) => Text(
          'A = ${model.countA}'
        ),
      ),
    ),
  );
}
```
**Question:**
Will a and b rebuild the same widget? Which is more performant?

**Comment by audkar** [comment]
So what answer is? :)

**Comment by brianegan** [comment]
Hey all, thanks for the patience! I'm actually giving a talk on ScopedModel tomorrow that will go in-depth on this topic and how scoped model works under the hood :) In short:

  - ScopedModel.of provides access to a particular Model. If you pass through `rebuildOnChange: true`, it will also tell the current Widget to call its `build` method when the model changes.
  - ScopedModelDescendant is a Widget that accesses a Model and can rebuild a portion of your UI in response to model changes. It actually uses ScopedModel.of under the hood! The reason you may want to use ScopedModelDescendant instead of ScopedModel.of directly: To limit rebuilds to a particular section of your Widget tree. E.g. rather than rebuilding an entire Scaffold, you can rebuild only a Text Widget.

To answer the Q directly:

Both I and IIa will rebuild the entire scaffold when the Model changes, because the `HomeModel.of(context)` is registering the current Widget's Element (context) as the target for rebuild when the Model changes.

IIb will only rebuild the `Text` Widget, because `ScopedModelDescendant` will create a new, smaller `context` that does not include the entire Scaffold.

**Comment by molon** [comment]
Thx, I understand. Just rebuild all widgets under the using **context**.
 (`HomeModel.of(context)` or 
```
ScopedModelDescendant<HomeModel>(
        builder: (context, child, model) { ... }
)
```

**Comment by alhassanmoses** [comment]
> Hey all, thanks for the patience! I'm actually giving a talk on ScopedModel tomorrow that will go in-depth on this topic and how scoped model works under the hood :) In short:
> 
> * ScopedModel.of provides access to a particular Model. If you pass through `rebuildOnChange: true`, it will also tell the current Widget to call its `build` method when the model changes.
> * ScopedModelDescendant is a Widget that accesses a Model and can rebuild a portion of your UI in response to model changes. It actually uses ScopedModel.of under the hood! The reason you may want to use ScopedModelDescendant instead of ScopedModel.of directly: To limit rebuilds to a particular section of your Widget tree. E.g. rather than rebuilding an entire Scaffold, you can rebuild only a Text Widget.
> 
> To answer the Q directly:
> 
> Both I and IIa will rebuild the entire scaffold when the Model changes, because the `HomeModel.of(context)` is registering the current Widget's Element (context) as the target for rebuild when the Model changes.
> 
> IIb will only rebuild the `Text` Widget, because `ScopedModelDescendant` will create a new, smaller `context` that does not include the entire Scaffold.

Thanks a lot, this really helped me figure out stuff in my project App data management, had a real hurdle choosing the most efficient one for me...
