### ISSUE TITLE
Ask for clarification: ScopedModel Vs Model ?

### ISSUE THREAD

**Issue by realtebo** [brianegan/scoped_model#57]
I'm followinf a Udemy course using your package, but  I thinks it's using a strange approach

Example: we have User model class

```
import 'package:meta/meta.dart';

class UserModel {
  final String id;
  final String email;
  final String password;

  UserModel({@required this.id, @required this.email, @required this.password});
}

```

Then we created a Scoped one

```
import 'package:scoped_model/scoped_model.dart';
import '../models/user_model.dart';

class ScopedUserModel extends Model {
  UserModel _authenticatedUsers;

  void login({String email, String password}) {
    _authenticatedUsers = UserModel(
        id: 'arararara', email: 'mirkotebaldi@yahoo.it', password: 'ararara');
    notifyListeners();
  }
}
```

But we also have Product Model and Product Scoped Model.

Than I give it up, when I must use both of them 

Why do we need a scoped class extending model and using our model class? To add listenable behaviour? This seems reasonable.

But what the right way to use both models without the chain of descendants? It's an hell.

Cource author is trying to use mixin, but Dart syntax for mixin already changed 3-4 times and now instructions are no more updated.

Asking for example in doc and a little more bit of theory

**Comment by brianegan** [comment]
Hey there -- thanks for writing in. Let me see if I can tackle some of these questions.

  > Why do we need a scoped class extending model and using our model class? To add listenable behaviour? This seems reasonable.

There are a couple reasons: First, I think the naming is confusing, but in general I think I understand what the course author is trying to do. Let me see if this helps as a clarification:

  1. I'd probably just call the `UserModel` a `User`. It's what many folks call a "Value Class" -- it just holds some information about a User.
  2. Then you have your `ScopedUserModel` -- again, I'd probably call this an `UserModel` instead. It's job is to take in some credentials and Log in a `User`.

So why would you separate these two? Well, if you only have 1 User that can't interact with any other users, you wouldn't need to! You could make them the same thing. 

However, for many apps, you'd want users to interact with each other, such as being able to view information about each other. Therefore, you can reuse the `User` class within another `Model`. For example, you could have another page that displays information about the person selling the product. You could create a `StoreOwnerModel` that knows how to fetch the `User` information about the Store Owner instead of a `UserModel` that knows how to log the current user in!

It's the same thing with the `ProductModel` and `ScopedProductModel`: One is used to hold the data, and one is used to fetch information from the correct data source. Again, you could think about reusing the `ProductModel` by using it inside another class that extends `Model`, such as a `ScopedStoreModel` that displays a `List<Product>` instead of a Single Product.

That's generally why you'd want to split them out -- for reusability! 

Second, being able to listen to the `Model` is very important. That's what allows ScopedModel to work! The Widgets listen to the Model for changes and rebuild when it does.

  > But what the right way to use both models without the chain of descendants? It's an hell.

I generally combine these two approaches:

https://github.com/brianegan/scoped_model#finding-the-model
https://github.com/brianegan/scoped_model#listening-to-multiple-models-in-a-build-function

This allows you to write the following and have the Widget rebuild when either model changes:

```dart
class MyWidget extends StatefulWidget {
  @override
  Widget build(BuildContext context) {
    final user = UserModel.of(context);
    final product = ProductModel.o(context);

    return Text('${user.name} purchased ${product.name} for ${product.price}');
  }
}
```

  > Cource author is trying to use mixin, but Dart syntax for mixin already changed 3-4 times and now instructions are no more updated.

I don't use mixins, I keep models separate. Sure, that requires you to nest one or two `ScopedModel` classes within one another, but I think you create a lot more problems by trying to mix multiple Models together into one God Model.

**Comment by realtebo** [comment]
Thanks, I hop to find a different solution, it's too much work to simply keep 2 chunks of code separated.

But, thanks for your work and for choosing to share with all, I see your plugin in the top 10 list, so it's of course an excellent solution!
