### ISSUE TITLE
Fetch Json.

### ISSUE THREAD

**Issue by uwejan** [brianegan/scoped_model#60]
Hi, sorry, for not sharing code, i am used to use flutter_flux, wanted to give scoped model a shot , and see if it fits better, here is my use case scenario, a list view initial data fetched by json, each item on the list view might be updated on the fly, i mean i am using some sort of websockt with a like button on an item of the list, when data comes back holding the new value, i can notice some sort of glitch where the item would pop down and up really fast updating the value, #11 i have read here, and did sth similar with condition on db not empty. Secondly, am using some sort of waking up connectivity if an internet connection went down, doing that i can see a request sent requiring new like value and the new values are back on console too, but UI never updates, i did call notify on my model where it gets the new values and update db. well. if am doing it right, dose that mean scoped model is not suitable for my use case?

**Comment by brianegan** [comment]
> i mean i am using some sort of websockt with a like button on an item of the list, when data comes back holding the new value, i can notice some sort of glitch where the item would pop down and up really fast updating the value

This could happen for a number of reasons, but it's super hard to say for sure without looking at your code. Do you have some logic that might display and empty `Container` or something if certain data is missing? Are you running an animation of some kind that's going wrong?

  > Secondly, am using some sort of waking up connectivity if an internet connection went down, doing that i can see a request sent requiring new like value and the new values are back on console too, but UI never updates, i did call notify on my model where it gets the new values and update db. well. if am doing it right, dose that mean scoped model is not suitable for my use case?

If you have a Model and call `notifyListeners`, but you are not seeing the Widget rebuild, this is probably because you are configuring `rebuildOnChange: false` somewhere. 

Overall, I'd say it's really hard to offer guidance on these problems without seeing the code. Do you happen to have some code you can share?
