### ISSUE TITLE
Fix suggestions suggests against Effective Dart

### ISSUE THREAD

**Issue by rrostt** [brianegan/scoped_model#62]
When using ScopedModelDescendent without a matching ScopedModel, using the right type of model, a fix is suggested: ```* Always use package imports. Ex: `import 'package:my_app/my_model.dart';```

However, this goes against the Effective Dart style guidelines. Is there a good reason to suggest otherwise in this instance? (https://www.dartlang.org/guides/language/effective-dart/usage#prefer-relative-paths-when-importing-libraries-within-your-own-packages-lib-directory)

**Comment by brianegan** [comment]
> Is there a good reason to suggest otherwise in this instance?

Fair point, but yes there is! In general, if you mix and match import styles, Dart will resolve the files as two separate things (it's super annoying). E.g. if you define a `CounterModel` in a file called `counter_model.dart`, and import it this way:

```
import 'package:my_app/counter_model.dart';
```

Dart will think the `CounterModel` class is different than this import:

```
import './counter_model.dart';
```

Since IntelliJ and VScode default to importing files with complete package paths, I recommended that course of action, since a lot of peeps were accidentally importing that same file in two different ways, but seeing super confusing type errors: "CounterModel is not of type CounterModel" kinda thing.
