### ISSUE TITLE
Error: could not find correct scoped model

### ISSUE THREAD

**Issue by saikuamar** [brianegan/scoped_model#67]
@brianegan since i was new to this scoped model concept . here i was struck i have a scaffoldand 3 tabs each is stateless widget and is separate file.show i wrap scopedmodel<Mymodel> above scaffold or can i wrap separately for each tab. my issue was i was i thrid tab and i try to bootom sheet. it show  could not  find correct scoped model in bottom sheet. i tried to wrap scopedModel<Mymodel> in tab itselt and tried at root level scaffold but same error. till now i dont know why iam getting this error where should i wrap the scopedmodel<> in such a situation.
please refer this stack question which i was asked  [https://stackoverflow.com/questions/55315845/unable-to-use-scoped-model-in-flutter-bottom-sheet-dialogs/55316017?noredirect=1#comment97370180_55316017](url)

**Comment by brianegan** [comment]
Heya @saikuamar -- Hrm, that's a funny one. Without seeing any code, it's' really hard to say what the issue could be. Do you have a project you can share?

**Comment by brianegan** [comment]
Hey there -- just took a look at the sample code you have, and think I found the problem:

The `ScopedModel` needs to be above the Scaffold, at the root of your app. Why? When you show a Modal sheet, that navigates to a new screen with a completely independent `BuildContext`. It is not a child of the Scaffold's `BuildContext`. To fix: Wrap your `MaterialApp` in the `ScopedModel` instead of the `Scaffold`.

**Comment by saikuamar** [comment]
@brianegan thanks for replying.can i wrap the modal bottom sheet with scopedModel<appModel> same that i wrapped in same page scaffold is that correct way of approach. and have a issue that in scopedModel<appModel>(
model:
) should i use the class name of the modal or the class object.
