### ISSUE TITLE
[Idea] It might be possible to use the Singleton design pattern, where `rebuildOnChange` is not required

### ISSUE THREAD

**Issue by devxpy** [brianegan/scoped_model#70]
Hey there! Thanks for this wonderful package. I have had a wonderful time using it so far.

---

After fiddling around for some time, I am wondering whether the [Singleton](https://en.wikipedia.org/wiki/Singleton_pattern) pattern can be used to our advantage in certain cases, like this one:

```dart
ScopedModel.of<CounterModel>(context, rebuildOnChange: false).increment();
```

The question: Can we get away with something like this?

```dart
class CounterModel extends Model {
  CounterModel._internal();

  static CounterModel _instance;

  static CounterModel get instance {
    if (_instance == null) {
      _instance = CounterModel._internal();
    }
    return _instance;
  }
  ...
}
```
```dart
MyApp(
    model: CounterModel.instance,
)
```
```dart
CounterModel.instance.increment();
```

Not only is it probably faster (as it avoids looking up the instance in the widget tree), but is also available at places where `context` might not be available.

---

I have modded the [example app](https://github.com/devxpy/scoped_model/blob/master/example/lib/main.dart), as a proof of concept.

Could you please shell out some time, to review my suggestion, and share your thoughts?

**Comment by brianegan** [comment]
Hey, glad ya like! Glad it's working well so far :)

You can certainly use the Singleton pattern and it's definitely the "right tool for the job" in some cases. That said, I don't think encouraging the Singleton pattern is a good fit for this library for a few of reasons:

  1. It's really important to use the `context` since that's the magic sauce that triggers rebuilds via InheritedWidgets.
  2. It provides two ways to do the same thing: `ScopedModel.of<MyModel>(context)` vs `MyModel.instance`.
  3. "Not only is it probably faster (as it avoids looking up the instance in the widget tree)" -- Looking up Widgets in the tree via the context is very fast and takes O(1) time after the initial lookup. Sure, it's not as fast as a direct object reference, but it's not a performance bottleneck. The Flutter team has specifically spent time to ensure this is the case, since so many core Widgets use this same pattern, such as the `Theme` widget.

Therefore, from my perspective, the most compelling reason for using a Singleton is to access the model in a place where you might not have access to the `BuildContext`. If that's the case and you can't solve the problem in another way (by passing the model to that function / class that needs the model  instead of finding it via the context), and you really only want 1 instance of the class, then certainly the singleton pattern could be an option!

**Comment by devxpy** [comment]
Thanks, that makes sense.

---

For reference, this is what I ended up using, and it works really well for me.

```dart
class Models {
  static var language = LanguageModel();

  static LanguageModel languageOf(BuildContext context) {
    return ScopedModel.of<LanguageModel>(context, rebuildOnChange: true);
  }

  static var filters = FilterDataModel();

  static FilterDataModel filtersOf(BuildContext context) {
    return ScopedModel.of<FilterDataModel>(context, rebuildOnChange: true);
  }

  static var lessons = LessonsModel();

  static IsConnectedModel isConnectedOf(BuildContext context) {
    return ScopedModel.of<IsConnectedModel>(context, rebuildOnChange: true);
  }

  static var isConnected = IsConnectedModel();

  static LessonsModel lessonsOf(BuildContext context) {
    return ScopedModel.of<LessonsModel>(context, rebuildOnChange: true);
  }
}

````
Then use it like so:
```dart
Models.language.value = "hello";
```
And where you do need rebuilds:
```
Text(Models.languageOf(context).value)
```
