### ISSUE TITLE
Flutter_web support

### ISSUE THREAD

**Issue by abbasidaniyal** [brianegan/scoped_model#76]
Missing support with flutter_web

**Comment by brianegan** [comment]
Hey hey -- flutter_web is currently a fork of Flutter, but that work will all be eventually merged into the main development branch. That means, in order to support flutter_web in the meantime, all Flutter packages would need to create their own forks that work with the flutter_web imports instead of the normal flutter imports, and then provide two different packages on pub, something like
`scoped_model` and `scoped_model_web`.

Unfortunately, that cloning will create a lot of overhead for the community. IMO, we should wait for flutter_web to merge into Flutter properly so packages, including this one, will work properly without this type of modification. It's a bit of a shame, but hopefully `flutter_web` will merge into flutter quite soon!
